import os
import markdown
from weasyprint import HTML, CSS
from app.config import get_settings

settings = get_settings()


def generate_pdf_from_markdown(
    md_content: str,
    report_id: str,
    client_id: str,
) -> str:
    """
    Generate a PDF file from markdown content.
    Returns the path to the generated PDF.
    """
    # Create output directory
    pdf_dir = os.path.join(settings.storage_path, "reports", client_id)
    os.makedirs(pdf_dir, exist_ok=True)
    
    pdf_path = os.path.join(pdf_dir, f"report-{report_id}.pdf")
    
    # Convert markdown to HTML
    html_content = markdown.markdown(
        md_content,
        extensions=["tables", "fenced_code", "toc"],
    )
    
    # Wrap in HTML document with styling
    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {{
                font-family: 'Helvetica Neue', Arial, sans-serif;
                font-size: 11pt;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 40px;
            }}
            h1 {{
                color: #1a1a1a;
                border-bottom: 2px solid #0066cc;
                padding-bottom: 10px;
                margin-top: 30px;
            }}
            h2 {{
                color: #333;
                border-bottom: 1px solid #ddd;
                padding-bottom: 5px;
                margin-top: 25px;
            }}
            h3 {{
                color: #555;
                margin-top: 20px;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
            }}
            th, td {{
                border: 1px solid #ddd;
                padding: 10px;
                text-align: left;
            }}
            th {{
                background-color: #f5f5f5;
                font-weight: bold;
            }}
            tr:nth-child(even) {{
                background-color: #fafafa;
            }}
            code {{
                background-color: #f4f4f4;
                padding: 2px 6px;
                border-radius: 3px;
                font-family: 'Courier New', monospace;
            }}
            pre {{
                background-color: #f4f4f4;
                padding: 15px;
                border-radius: 5px;
                overflow-x: auto;
            }}
            .warning {{
                background-color: #fff3cd;
                border-left: 4px solid #ffc107;
                padding: 10px 15px;
                margin: 15px 0;
            }}
            .error {{
                background-color: #f8d7da;
                border-left: 4px solid #dc3545;
                padding: 10px 15px;
                margin: 15px 0;
            }}
            .success {{
                background-color: #d4edda;
                border-left: 4px solid #28a745;
                padding: 10px 15px;
                margin: 15px 0;
            }}
            footer {{
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #ddd;
                font-size: 9pt;
                color: #666;
                text-align: center;
            }}
        </style>
    </head>
    <body>
        {html_content}
        <footer>
            <p><strong>Disclaimer:</strong> This document is generated by Ledgerly for preparation and workflow 
            automation purposes only. It does NOT constitute tax filing, certification, or legal opinion.</p>
            <p>Generated by Ledgerly • Report ID: {report_id}</p>
        </footer>
    </body>
    </html>
    """
    
    # Generate PDF
    HTML(string=full_html).write_pdf(pdf_path)
    
    return pdf_path
